name: Build with Arduino CLI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install Board Definitions
        run:  bash ${GITHUB_WORKSPACE}/setup.sh

      - name: Compile app
        run:  bash ${GITHUB_WORKSPACE}/compile.sh

      - name: Merge Bin
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: release-v5.4
          target: esp32
          command: |
            esptool.py --chip esp32 merge_bin --output build/PSP-Bluetooth-Firmware-merged.bin --flash_mode dio --flash_freq keep --flash_size 4MB 0x1000 build/PSPBluetooth-firmware.ino.bootloader.bin 0x8000 build/PSPBluetooth-firmware.ino.partitions.bin 0x10000 build/PSPBluetooth-firmware.ino.bin
      
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          working_directory: build
          files: |
            PSPBluetooth-firmware.ino.bin
            PSPBluetooth-firmware.ino.bootloader.bin
            PSPBluetooth-firmware.ino.partitions.bin
            PSP-Bluetooth-Firmware-merged.bin

