name: Build with ESP-IDF v5.4

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Arduino build ESP32
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32
        command: "idf.py set-target esp32 && idf.py build"
      
    - name: Merge Bin
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32
        command: |
          esptool.py --chip esp32 merge_bin --output build/PSP-Bluetooth-Firmware-merged.bin --flash_mode dio --flash_freq keep --flash_size 4MB 0x1000 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0x10000 build/PSP-Bluetooth-Firmware.bin
    
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        prerelease: true
        files: | 
          build/PSP-Bluetooth-Firmware.bin
          build/PSP-Bluetooth-Firmware-merged.bin
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin

